apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        resources:
          limits:
            cpu: "300m"
            memory: 200Mi
          requests:
            cpu: "100m"
            memory: 100Mi
