apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.14.2
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        resources:
          limits:
            cpu: "300m"
            memory: 200Mi
          requests:
            cpu: "150m"
            memory: 100Mi
