apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-demo-3
spec:
  limits:
  - type: Container
    max:
      cpu: 2
      memory: 500Mi
    min:
      cpu: 100m
      memory: 50Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
