apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpu-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "300m"
        memory: 200Mi
      requests:
        cpu: "300m"
        memory: 200Mi
