apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-rq
spec:
  hard:
    configmaps: "2"
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
