# Local Registry configMap.
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "registry.example.com:5000"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"