apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v2
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: v2
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-home-dir
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-home-dir
        configMap:
          name: nginx-v2
