apiVersion: v1
kind: Service
metadata:
  name: svc-multi-container-port
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 80
