apiVersion: v1
kind: Pod
metadata:
  name: ambassador-container-demo
spec:
  containers:
  - name: myapp
    image: alpine:3.2
    command: ["sleep", "9999999"]
  - name: kubectl-proxy
    image: bitnami/kubectl:latest
    command: ["kubectl"]
    args:
      - "proxy"