# create a cluster with the local registry enabled in containerd
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.example.com:5000"]
    endpoint = ["http://registry.example.com:5000"]
nodes:
- role: control-plane
- role: worker