apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-memory-2
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: stress-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - image: vish/stress
        name: stress
        resources:
          limits:
            memory: "100Mi"
          requests:
            memory: "50Mi"
        args:
          - -mem-total
          - "200Mi"
          - -mem-alloc-size
          - "20Mi"
          - -mem-alloc-sleep
          - "6s"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
