apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpu-test-liveness-probe
spec:
  containers:
  - name: nginx-liveness-probe
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      httpGet:
        port: 80
        path: /
    resources:
      limits:
        cpu: "100m"
      requests:
        cpu: "50m"
